; Though `par2` will produce tighter error bounds than `par1`,
; it doesn't mean that `par2` is better that `par1`. The difference of
; errors is generated by the backward os the interval arithmetic system.
; A well defined functioning system should produce the same output for
; these two procedure.
